export const complaints = [
  {
    id: "C001",
    complaint_number: "20251101-001",
    status: "تحت المعالجة",
    date: "2025-10-28",
    customer_name: "أحمد علي",
    vendor_id: "1",
    vendor_name: "كار بارتي هاب",
    title: "تأخر استلام الطلب",
    description:
      "قمت بطلب منتج من كار بارتي هاب منذ أسبوعين ولم يتم تسليمه حتى الآن رغم تأكيد الشحن.",
    // admin_response_title: "تم التواصل مع شركة الشحن",
    // admin_response_description: "تم تحديد موعد جديد لتسليم الطلب خلال يومين.",
    images: ["/uploads/complaints/C001_1.jpg"],
  },
  {
    id: "C002",
    complaint_number: "20251101-002",
    status: "تم التواصل مع التاجر",
    date: "2025-10-25",
    customer_name: "نورة السبيعي",
    vendor_id: "2",
    vendor_name: "جير برو",
    title: "منتج غير مطابق للوصف",
    description:
      "المنتج الذي وصلني من جير برو يختلف عن الصور المنشورة في الموقع من حيث اللون والجودة.",
    admin_response_title: "تم التحقق من المورد",
    admin_response_description:
      "تم التواصل مع التاجر وسيتم إرسال منتج بديل أو استرجاع المبلغ خلال 3 أيام عمل.",
    images: ["/uploads/complaints/C002_1.jpg"],
  },
  {
    id: "C003",
    complaint_number: "20251101-003",
    status: "تم المعالجة",
    date: "2025-10-22",
    customer_name: "محمد القحطاني",
    vendor_id: "3",
    vendor_name: "أوتو فيكس",
    title: "طلب ملغي بدون سبب",
    description:
      "تم إلغاء طلبي من أوتو فيكس دون إعلامي بالسبب رغم أن الدفع تم بنجاح.",
    admin_response_title: "تم حل المشكلة",
    admin_response_description:
      "تم إعادة تفعيل الطلب وإرساله من جديد مع خصم 10٪ كتعويض.",
    images: [],
  },
  {
    id: "C004",
    complaint_number: "20251101-004",
    status: "تحت المعالجة",
    date: "2025-10-29",
    customer_name: "فيصل الهاجري",
    vendor_id: "5",
    vendor_name: "الجميل للسيارات",
    title: "خطأ في الفاتورة",
    description:
      "تم احتساب سعر المنتج مرتين في الفاتورة النهائية من الجميل للسيارات.",
    // admin_response_title: "يتم مراجعة الحسابات",
    // admin_response_description: "جاري تصحيح الفاتورة خلال 24 ساعة.",
    images: [],
  },
  {
    id: "C005",
    complaint_number: "20251101-005",
    status: "تم التواصل مع التاجر",
    date: "2025-10-27",
    customer_name: "عبدالله الشمري",
    vendor_id: "7",
    vendor_name: "راشد تفاحة",
    title: "سوء تعامل من موظف المتجر",
    description:
      "أثناء التواصل مع الدعم الفني في راشد تفاحة، كان الموظف غير متعاون.",
    admin_response_title: "تم اتخاذ الإجراء اللازم",
    admin_response_description:
      "تم تنبيه التاجر رسميًا على تحسين أسلوب التعامل مع العملاء.",
    images: [],
  },
  {
    id: "C006",
    complaint_number: "20251101-006",
    status: "تم المعالجة",
    date: "2025-10-20",
    customer_name: "حسن الغامدي",
    vendor_id: "8",
    vendor_name: "دوبل إم",
    title: "مشكلة في الدفع الإلكتروني",
    description:
      "حدث خطأ أثناء عملية الدفع لمتجر دوبل إم وتم خصم المبلغ دون تأكيد الطلب.",
    admin_response_title: "تم استرجاع المبلغ",
    admin_response_description:
      "تم استرجاع المبلغ إلى حساب العميل خلال 48 ساعة.",
    images: ["/uploads/complaints/C006_1.jpg"],
  },
  {
    id: "C007",
    complaint_number: "20251101-007",
    status: "تحت المعالجة",
    date: "2025-10-31",
    customer_name: "ريم العنزي",
    vendor_id: "9",
    vendor_name: "المتميز لقطع الغيار",
    title: "مشكلة في تسجيل الدخول إلى الحساب",
    description:
      "لا أستطيع الدخول إلى حسابي في موقع المتميز لقطع الغيار رغم أن كلمة المرور صحيحة.",
    admin_response_title: "قيد التحقق الفني",
    admin_response_description: "يتم فحص الحساب من قبل فريق الدعم.",
    images: [],
  },
  {
    id: "C008",
    complaint_number: "20251101-008",
    status: "تم التواصل مع التاجر",
    date: "2025-10-30",
    customer_name: "سارة المطيري",
    vendor_id: "10",
    vendor_name: "أبو غنيمة أدوات السيارات",
    title: "المنتج تالف عند الاستلام",
    description: "المنتج من أبو غنيمة وصل مكسور جزئيًا رغم أن التغليف سليم.",
    // admin_response_title: "تم التواصل مع البائع",
    // admin_response_description:
    //   "تم فتح بلاغ ضد شركة التوصيل وسيتم إرسال منتج بديل مجانًا.",
    images: ["/uploads/complaints/C008_1.jpg"],
  },
  {
    id: "C009",
    complaint_number: "20251101-009",
    status: "تم المعالجة",
    date: "2025-10-15",
    customer_name: "نواف الحربي",
    vendor_id: "12",
    vendor_name: "نوسير لقطع الغيار",
    title: "عدم ظهور الطلب في الصفحة الشخصية",
    description:
      "طلبت منتجًا من نوسير لقطع الغيار لكنه لا يظهر في صفحة الطلبات.",
    admin_response_title: "تم إصلاح الخطأ التقني",
    admin_response_description: "تمت إضافة الطلب يدويًا لحساب العميل.",
    images: [],
  },
  {
    id: "C010",
    complaint_number: "20251101-010",
    status: "تحت المعالجة",
    date: "2025-10-24",
    customer_name: "ليان العتيبي",
    vendor_id: "16",
    vendor_name: "كار سبير بارتي",
    title: "مشكلة في تتبع الطلب",
    description: "رابط تتبع الطلب من كار سبير بارتي لا يعمل منذ يومين.",
    admin_response_title: "جارٍ مراجعة النظام",
    admin_response_description:
      "سيتم إصلاح الرابط خلال 12 ساعة وإرسال تحديث للعميل.",
    images: [],
  },
];
