export const invoices = [
  {
    id: "1",
    invoice_number: "INV-1001",
    order_number: "ORD-5001",
    date: "2025-11-01",
    total_amount: 450.75,
    currency: "SAR",
    vendor_name: "كار بارتي هاب",
    payment_method: "بطاقة",
    status: "مدفوعة",
    products: [
      { product_id: "P-101", name: "منتج 1", quantity: 2, price: 100.0 },
      { product_id: "P-102", name: "منتج 2", quantity: 1, price: 250.75 },
    ],
  },
  {
    id: "2",
    invoice_number: "INV-1002",
    order_number: "ORD-5002",
    date: "2025-11-05",
    total_amount: 300.0,
    currency: "SAR",
    vendor_name: "جير برو",
    payment_method: "كاش",
    status: "بانتظار الدفع",
    products: [
      { product_id: "P-103", name: "منتج 3", quantity: 3, price: 100.0 },
    ],
  },
  {
    id: "3",
    invoice_number: "INV-1003",
    order_number: "ORD-5003",
    date: "2025-10-15",
    total_amount: 620.5,
    currency: "SAR",
    vendor_name: "أوتو فيكس",
    payment_method: "بطاقة",
    status: "مدفوعة",
    products: [
      { product_id: "P-104", name: "منتج 4", quantity: 1, price: 200.0 },
      { product_id: "P-105", name: "منتج 5", quantity: 2, price: 210.25 },
    ],
  },
  {
    id: "4",
    invoice_number: "INV-1004",
    order_number: "ORD-5004",
    date: "2025-10-20",
    total_amount: 150.0,
    currency: "SAR",
    vendor_name: "أوتو بارتي برو",
    payment_method: "باي بال",
    status: "مدفوعة",
    products: [
      { product_id: "P-106", name: "منتج 6", quantity: 1, price: 150.0 },
    ],
  },
  {
    id: "5",
    invoice_number: "INV-1005",
    order_number: "ORD-5005",
    date: "2025-08-12",
    total_amount: 780.0,
    currency: "SAR",
    vendor_name: "الجميل للسيارات",
    payment_method: "بطاقة",
    status: "مدفوعة",
    products: [
      { product_id: "P-107", name: "منتج 7", quantity: 3, price: 260.0 },
    ],
  },
  {
    id: "6",
    invoice_number: "INV-1006",
    order_number: "ORD-5006",
    date: "2025-08-20",
    total_amount: 400.0,
    currency: "SAR",
    vendor_name: "أوتو بارتي",
    payment_method: "كاش",
    status: "بانتظار الدفع",
    products: [
      { product_id: "P-108", name: "منتج 8", quantity: 2, price: 200.0 },
    ],
  },
  {
    id: "7",
    invoice_number: "INV-1007",
    order_number: "ORD-5007",
    date: "2025-05-05",
    total_amount: 555.5,
    currency: "SAR",
    vendor_name: "راشد تفاحة",
    payment_method: "بطاقة",
    status: "مدفوعة",
    products: [
      { product_id: "P-109", name: "منتج 9", quantity: 1, price: 255.5 },
      { product_id: "P-110", name: "منتج 10", quantity: 1, price: 300.0 },
    ],
  },
  {
    id: "8",
    invoice_number: "INV-1008",
    order_number: "ORD-5008",
    date: "2025-05-18",
    total_amount: 350.0,
    currency: "SAR",
    vendor_name: "دوبل إم",
    payment_method: "باي بال",
    status: "مدفوعة",
    products: [
      { product_id: "P-111", name: "منتج 11", quantity: 2, price: 175.0 },
    ],
  },
  {
    id: "9",
    invoice_number: "INV-1009",
    order_number: "ORD-5009",
    date: "2025-11-10",
    total_amount: 920.0,
    currency: "SAR",
    vendor_name: "المتميز لقطع الغيار",
    payment_method: "بطاقة",
    status: "مدفوعة",
    products: [
      { product_id: "P-112", name: "منتج 12", quantity: 4, price: 230.0 },
    ],
  },
  {
    id: "10",
    invoice_number: "INV-1010",
    order_number: "ORD-5010",
    date: "2025-10-28",
    total_amount: 600.0,
    currency: "SAR",
    vendor_name: "أبو غنيمة أدوات السيارات",
    payment_method: "كاش",
    status: "بانتظار الدفع",
    products: [
      { product_id: "P-113", name: "منتج 13", quantity: 3, price: 200.0 },
    ],
  },
];
