export const orders_data = [
  {
    id: "1",
    order_number: "ORD-1001",
    status: "في الإنتظار",
    has_quotes: true,
    quotes_number: 3,
    date: "2025-11-01",
    address: "الرياض - حي العليا - شارع التحلية",
    car_name: "Toyota",
    car_model: "Camry 2021",
    merchant_name: "كار بارتي هاب",
    merchant_image: "/vendors/CarPartsHub.png",
    merchant_address: "الرياض - حي العليا - شارع التحلية",
    merchant_rating: 4.6,
    merchant_phone: "+966512345678",
    merchant_id: "4",
    products: [
      {
        name: "فلتر هواء",
        quantity: 2,
        price: 120,
        image: "/car_parts/battery.jpg",
      },
      { name: "زيت محرك", quantity: 1, price: 80, image: "/car_parts/oil.jpg" },
    ],
    total_price: 320,
  },
  {
    id: "2",
    order_number: "ORD-1002",
    status: "في الإنتظار",
    has_quotes: false,
    date: "2025-11-03",
    address: "الدمام - حي الريان",
    car_name: "Hyundai",
    car_model: "Tucson 2022",
    merchant_name: "أوتو فيكس السعودية",
    merchant_image: "/vendors/AutoFix.png",
    merchant_address: "جدة - حي الروضة - طريق المدينة",
    merchant_rating: 4.8,
    merchant_phone: "+966501234567",
    merchant_id: "3",
    products: [
      {
        name: "مصفي وقود",
        quantity: 1,
        price: 100,
        image: "/car_parts/filter.jpg",
      },
      { name: "بطارية", quantity: 1, price: 350, image: "/car_parts/plug.jpg" },
    ],
    total_price: 450,
  },
  {
    id: "3",
    order_number: "ORD-1003",
    status: "قيد الدفع",
    date: "2025-10-29",
    address: "جدة - حي الروضة - طريق المدينة",
    car_name: "BMW",
    car_model: "X5 2022",
    merchant_name: "نوسير",
    merchant_image: "/vendors/Nossir.png",
    merchant_address: "الدمام - حي الشاطئ",
    merchant_rating: 4.3,
    merchant_phone: "+966553214567",
    merchant_id: "12",
    products: [
      { name: "بطارية", quantity: 1, price: 400, image: "/car_parts/plug.jpg" },
      {
        name: "إطارات",
        quantity: 4,
        price: 600,
        image: "/car_parts/tyres.jpg",
      },
    ],
    total_price: 2800,
  },
  {
    id: "4",
    order_number: "ORD-1004",
    status: "قيد الدفع",
    date: "2025-10-15",
    address: "الدمام - حي الشاطئ",
    car_name: "Hyundai",
    car_model: "Elantra 2020",
    merchant_name: "جير برو",
    merchant_image: "/vendors/GearPro.png",
    merchant_address: "الدمام - حي الريان",
    merchant_rating: 4.5,
    merchant_phone: "+966509876543",
    merchant_id: "2",
    products: [
      {
        name: "فلتر زيت",
        quantity: 1,
        price: 90,
        image: "/car_parts/radiator.jpg",
      },
      { name: "شمعات", quantity: 4, price: 70, image: "/car_parts/plug.jpg" },
    ],
    total_price: 370,
  },
  {
    id: "5",
    order_number: "ORD-1005",
    status: "حالية",
    internal_status: "جاري التجهيز",
    date: "2025-11-02",
    address: "الرياض - حي النرجس",
    car_name: "Nissan",
    car_model: "Altima 2021",
    merchant_name: "كار بارتي هاب",
    merchant_image: "/vendors/CarPartsHub.png",
    merchant_address: "الرياض - حي العليا - شارع التحلية",
    merchant_rating: 4.6,
    merchant_phone: "+966512345678",
    merchant_id: "4",
    products: [
      {
        name: "مرايا جانبية",
        quantity: 2,
        price: 250,
        image: "/car_parts/compressor.jpg",
      },
    ],
    total_price: 500,
  },
  {
    id: "6",
    order_number: "ORD-1006",
    status: "حالية",
    internal_status: "تم التجهيز",
    date: "2025-10-31",
    address: "جدة - حي الشاطئ",
    car_name: "Mercedes",
    car_model: "C200 2023",
    merchant_name: "نوسير",
    merchant_image: "/vendors/Nossir.png",
    merchant_address: "الدمام - حي الشاطئ",
    merchant_rating: 4.3,
    merchant_phone: "+966553214567",
    merchant_id: "12",
    products: [
      { name: "فرامل", quantity: 4, price: 200, image: "/car_parts/brake.jpg" },
      {
        name: "زيت ناقل حركة",
        quantity: 1,
        price: 150,
        image: "/car_parts/oil.jpg",
      },
    ],
    total_price: 950,
  },
  {
    id: "7",
    order_number: "ORD-1007",
    status: "حالية",
    internal_status: "تم إرساله للشحن",
    date: "2025-10-28",
    address: "الدمام - حي الريان",
    car_name: "Kia",
    car_model: "Sportage 2022",
    merchant_name: "أوتو فيكس السعودية",
    merchant_image: "/vendors/AutoFix.png",
    merchant_address: "جدة - حي الروضة - طريق المدينة",
    merchant_rating: 4.8,
    merchant_phone: "+966501234567",
    merchant_id: "3",
    products: [
      {
        name: "بطانة مكابح",
        quantity: 4,
        price: 180,
        image: "/car_parts/brake.jpg",
      },
    ],
    total_price: 720,
  },
  {
    id: "8",
    order_number: "ORD-1008",
    status: "حالية",
    internal_status: "تم التسليم",
    date: "2025-10-25",
    address: "الرياض - حي الملقا",
    car_name: "Chevrolet",
    car_model: "Malibu 2021",
    merchant_name: "كار بارتي هاب",
    merchant_image: "/vendors/CarPartsHub.png",
    merchant_address: "الرياض - حي العليا - شارع التحلية",
    merchant_rating: 4.6,
    merchant_phone: "+966512345678",
    merchant_id: "4",
    products: [
      {
        name: "فلاتر هواء و زيت",
        quantity: 2,
        price: 130,
        image: "/car_parts/filter.jpg",
      },
    ],
    total_price: 260,
  },
  {
    id: "9",
    order_number: "ORD-1009",
    status: "منتهية",
    internal_status: "تم التسليم",
    date: "2025-09-15",
    address: "مكة - حي العزيزية",
    car_name: "Honda",
    car_model: "Civic 2020",
    merchant_name: "نوسير",
    merchant_image: "/vendors/Nossir.png",
    merchant_address: "الدمام - حي الشاطئ",
    merchant_rating: 4.3,
    merchant_phone: "+966553214567",
    merchant_id: "12",
    rating: 5,
    products: [
      { name: "بطارية", quantity: 1, price: 300, image: "/car_parts/plug.jpg" },
      {
        name: "مرايا جانبية",
        quantity: 2,
        price: 200,
        image: "/car_parts/compressor.jpg",
      },
    ],
    total_price: 700,
  },
  {
    id: "10",
    order_number: "ORD-1010",
    status: "منتهية",
    internal_status: "تم التسليم",
    date: "2025-08-20",
    address: "المدينة المنورة - حي قباء",
    car_name: "Ford",
    car_model: "Focus 2019",
    merchant_name: "أوتو فيكس السعودية",
    merchant_image: "/vendors/AutoFix.png",
    merchant_address: "جدة - حي الروضة - طريق المدينة",
    merchant_rating: 4.8,
    merchant_phone: "+966501234567",
    merchant_id: "3",
    rating: 4,
    products: [
      { name: "زيت محرك", quantity: 1, price: 90, image: "/car_parts/oil.jpg" },
    ],
    total_price: 90,
  },
  {
    id: "11",
    order_number: "ORD-1011",
    status: "منتهية",
    internal_status: "تم التسليم",
    date: "2025-07-02",
    address: "الرياض - حي اليرموك",
    car_name: "Mazda",
    car_model: "CX-5 2021",
    merchant_name: "كار بارتي هاب",
    merchant_image: "/vendors/CarPartsHub.png",
    merchant_address: "الرياض - حي العليا - شارع التحلية",
    merchant_rating: 4.6,
    merchant_phone: "+966512345678",
    merchant_id: "4",
    products: [
      {
        name: "فلتر هواء",
        quantity: 1,
        price: 110,
        image: "/car_parts/filter.jpg",
      },
      { name: "شمعات", quantity: 4, price: 70, image: "/car_parts/plug.jpg" },
    ],
    total_price: 390,
  },
];
