export const parts_data = [
  {
    id: "SP-001",
    name: "فلتر زيت المحرك",
    type: "فلتر",
    condition: "جديد (أصلي)",
    image: "/car_parts/oil.jpg",
    stock: 45,
    car_brands: [
      { ar: "تويوتا", en: "Toyota" },
      { ar: "مازدا", en: "Mazda" },
      { ar: "نيسان", en: "Nissan" },
    ],
  },
  {
    id: "SP-002",
    name: "فلتر هواء",
    type: "فلتر",
    condition: "جديد (تجاري)",
    image: "/car_parts/filter.jpg",
    stock: 60,
    car_brands: [
      { ar: "تويوتا", en: "Toyota" },
      { ar: "هوندا", en: "Honda" },
      { ar: "ميتسوبيشي", en: "Mitsubishi" },
    ],
  },
  {
    id: "SP-003",
    name: "بطارية سيارة 70 أمبير",
    type: "بطارية",
    condition: "جديد (أصلي)",
    image: "/car_parts/battery.jpg",
    stock: 25,
    car_brands: [
      { ar: "تويوتا", en: "Toyota" },
      { ar: "مازدا", en: "Mazda" },
      { ar: "نيسان", en: "Nissan" },
      { ar: "هيونداي", en: "Hyundai" },
    ],
  },
  {
    id: "SP-004",
    name: "بطارية 55 أمبير",
    type: "بطارية",
    condition: "جديد (تجاري)",
    image: "/car_parts/battery.jpg",
    stock: 40,
    car_brands: [
      { ar: "هوندا", en: "Honda" },
      { ar: "تويوتا", en: "Toyota" },
    ],
  },
  {
    id: "SP-005",
    name: "إطارات مقاس 17",
    type: "إطار",
    condition: "جديد (أصلي)",
    image: "/car_parts/tyres.jpg",
    stock: 18,
    car_brands: [
      { ar: "تويوتا", en: "Toyota" },
      { ar: "لكزس", en: "Lexus" },
    ],
  },
  {
    id: "SP-006",
    name: "إطارات مقاس 16",
    type: "إطار",
    condition: "جديد (تجاري)",
    image: "/car_parts/tyres.jpg",
    stock: 28,
    car_brands: [
      { ar: "هيونداي", en: "Hyundai" },
      { ar: "كيا", en: "Kia" },
    ],
  },
  {
    id: "SP-007",
    name: "جنوط رياضية 18 بوصة",
    type: "جنوط",
    condition: "جديد (أصلي)",
    image: "/car_parts/tyres.jpg",
    stock: 12,
    car_brands: [
      { ar: "تويوتا", en: "Toyota" },
      { ar: "مرسيدس", en: "Mercedes" },
    ],
  },
  {
    id: "SP-008",
    name: "جنوط مقاس 17 بوصة",
    type: "جنوط",
    condition: "تشليح",
    image: "/car_parts/tyres.jpg",
    stock: 6,
    car_brands: [
      { ar: "نيسان", en: "Nissan" },
      { ar: "هوندا", en: "Honda" },
    ],
  },
  {
    id: "SP-009",
    name: "مساعد أمامي ياباني",
    type: "مساعد",
    condition: "جديد (تجاري)",
    image: "/car_parts/plug.jpg",
    stock: 22,
    car_brands: [
      { ar: "تويوتا", en: "Toyota" },
      { ar: "مازدا", en: "Mazda" },
    ],
  },
  {
    id: "SP-010",
    name: "مساعد خلفي ألماني",
    type: "مساعد",
    condition: "جديد (أصلي)",
    image: "/car_parts/plug.jpg",
    stock: 19,
    car_brands: [
      { ar: "مرسيدس", en: "Mercedes" },
      { ar: "بي إم دبليو", en: "BMW" },
    ],
  },
  {
    id: "SP-011",
    name: "ديسك فرامل أمامي",
    type: "فرامل",
    condition: "جديد (تجاري)",
    image: "/car_parts/brake.jpg",
    stock: 30,
    car_brands: [
      { ar: "تويوتا", en: "Toyota" },
      { ar: "هوندا", en: "Honda" },
      { ar: "كيا", en: "Kia" },
    ],
  },
  {
    id: "SP-012",
    name: "تيل فرامل خلفي",
    type: "فرامل",
    condition: "جديد (أصلي)",
    image: "/car_parts/brake.jpg",
    stock: 27,
    car_brands: [
      { ar: "نيسان", en: "Nissan" },
      { ar: "مازدا", en: "Mazda" },
    ],
  },
  {
    id: "SP-013",
    name: "رديتر ماء تويوتا",
    type: "رديتر",
    condition: "جديد (أصلي)",
    image: "/car_parts/radiator.jpg",
    stock: 11,
    car_brands: [{ ar: "تويوتا", en: "Toyota" }],
  },
  {
    id: "SP-014",
    name: "رديتر مكيف نيسان",
    type: "رديتر",
    condition: "تشليح",
    image: "/car_parts/radiator.jpg",
    stock: 7,
    car_brands: [{ ar: "نيسان", en: "Nissan" }],
  },
  {
    id: "SP-015",
    name: "كمبروسر مكيف",
    type: "مكيف",
    condition: "جديد (تجاري)",
    image: "/car_parts/compressor.jpg",
    stock: 13,
    car_brands: [
      { ar: "تويوتا", en: "Toyota" },
      { ar: "هيونداي", en: "Hyundai" },
    ],
  },
  {
    id: "SP-016",
    name: "كمبروسر مكيف أصلي",
    type: "مكيف",
    condition: "جديد (أصلي)",
    image: "/car_parts/compressor.jpg",
    stock: 8,
    car_brands: [
      { ar: "مرسيدس", en: "Mercedes" },
      { ar: "بي إم دبليو", en: "BMW" },
    ],
  },
  {
    id: "SP-017",
    name: "لمبة أمامية LED",
    type: "إنارة",
    condition: "جديد (تجاري)",
    image: "/car_parts/led.jpg",
    stock: 33,
    car_brands: [
      { ar: "تويوتا", en: "Toyota" },
      { ar: "هوندا", en: "Honda" },
    ],
  },
  {
    id: "SP-018",
    name: "كشاف خلفي تويوتا",
    type: "إنارة",
    condition: "تشليح",
    image: "/car_parts/led.jpg",
    stock: 4,
    car_brands: [{ ar: "تويوتا", en: "Toyota" }],
  },
  {
    id: "SP-019",
    name: "مراية جانبية كهربائية",
    type: "مراية",
    condition: "جديد (أصلي)",
    image: "/car_parts/mirror.jpg",
    stock: 16,
    car_brands: [
      { ar: "تويوتا", en: "Toyota" },
      { ar: "مازدا", en: "Mazda" },
    ],
  },
  {
    id: "SP-020",
    name: "مراية جانبية عادية",
    type: "مراية",
    condition: "جديد (تجاري)",
    image: "/car_parts/mirror.jpg",
    stock: 22,
    car_brands: [
      { ar: "نيسان", en: "Nissan" },
      { ar: "هيونداي", en: "Hyundai" },
    ],
  },
  {
    id: "SP-021",
    name: "غطاء تانكي بنزين",
    type: "هيكل",
    condition: "تشليح",
    image: "/car_parts/cover.jpg",
    stock: 9,
    car_brands: [
      { ar: "تويوتا", en: "Toyota" },
      { ar: "نيسان", en: "Nissan" },
    ],
  },
  {
    id: "SP-022",
    name: "غطاء محرك أمامي",
    type: "هيكل",
    condition: "جديد (تجاري)",
    image: "/car_parts/cover.jpg",
    stock: 15,
    car_brands: [
      { ar: "هوندا", en: "Honda" },
      { ar: "كيا", en: "Kia" },
    ],
  },
  {
    id: "SP-023",
    name: "صدام أمامي كورولا",
    type: "هيكل",
    condition: "جديد (أصلي)",
    image: "/car_parts/led.jpg",
    stock: 14,
    car_brands: [{ ar: "تويوتا", en: "Toyota" }],
  },
  {
    id: "SP-024",
    name: "رديتر زيت",
    type: "رديتر",
    condition: "جديد (أصلي)",
    image: "/car_parts/radiator.jpg",
    stock: 10,
    car_brands: [
      { ar: "تويوتا", en: "Toyota" },
      { ar: "هوندا", en: "Honda" },
    ],
  },
  {
    id: "SP-025",
    name: "سير محرك",
    type: "محرك",
    condition: "جديد (تجاري)",
    image: "/car_parts/plug.jpg",
    stock: 31,
    car_brands: [
      { ar: "تويوتا", en: "Toyota" },
      { ar: "نيسان", en: "Nissan" },
    ],
  },
  {
    id: "SP-026",
    name: "طقم بواجي",
    type: "محرك",
    condition: "جديد (أصلي)",
    image: "/car_parts/plug.jpg",
    stock: 24,
    car_brands: [
      { ar: "هوندا", en: "Honda" },
      { ar: "تويوتا", en: "Toyota" },
    ],
  },
  {
    id: "SP-027",
    name: "دينمو شحن",
    type: "كهرباء",
    condition: "تشليح",
    image: "/car_parts/battery.jpg",
    stock: 5,
    car_brands: [
      { ar: "نيسان", en: "Nissan" },
      { ar: "مازدا", en: "Mazda" },
    ],
  },
  {
    id: "SP-028",
    name: "رديتر هواء توربو",
    type: "توربو",
    condition: "جديد (تجاري)",
    image: "/car_parts/radiator.jpg",
    stock: 9,
    car_brands: [
      { ar: "تويوتا", en: "Toyota" },
      { ar: "هوندا", en: "Honda" },
    ],
  },
  {
    id: "SP-029",
    name: "شاحن توربيني",
    type: "توربو",
    condition: "جديد (أصلي)",
    image: "/car_parts/battery.jpg",
    stock: 6,
    car_brands: [
      { ar: "مرسيدس", en: "Mercedes" },
      { ar: "بي إم دبليو", en: "BMW" },
    ],
  },
  {
    id: "SP-030",
    name: "رديتر مكيف هوندا",
    type: "رديتر",
    condition: "تشليح",
    image: "/car_parts/radiator.jpg",
    stock: 3,
    car_brands: [{ ar: "هوندا", en: "Honda" }],
  },
];
