export const price_offers = [
  {
    offer_id: "OFR-001",
    id: "4",
    merchant_name: "كار بارتي هاب",
    merchant_image: "/vendors/CarPartsHub.png",
    merchant_address: "الرياض - حي العليا - شارع التحلية",
    merchant_rating: 4.6,
    merchant_phone: "+966512345678",
    distance_km: 3.4,
    total_items: 3,
    price_per_item: 180,
    total_price: 540,
    delivery_method: "توصيل بواسطة المنصة",
    notes: "يُرجى التأكيد خلال 24 ساعة لضمان توفر القطع.",
    items: [
      {
        id: "1",
        name: "فلتر هواء",
        price: 150,
        quantity: 1,
        image: "https://images.unsplash.com/photo-1615397349754-c5b2d3f3c9cc",
      },
      {
        id: "2",
        name: "زيت محرك",
        price: 200,
        quantity: 1,
        image: "https://images.unsplash.com/photo-1612831455542-388b1d9f1a0c",
      },
      {
        id: "3",
        name: "بطارية",
        price: 190,
        quantity: 1,
        image: "https://images.unsplash.com/photo-1607860108855-2f6bfecc8a3b",
      },
    ],
  },
  {
    offer_id: "OFR-002",
    id: "3",
    merchant_name: "أوتو فيكس السعودية",
    merchant_image: "/vendors/AutoFix.png",
    merchant_address: "جدة - حي الروضة - طريق المدينة",
    merchant_rating: 4.8,
    merchant_phone: "+966501234567",
    distance_km: 7.2,
    total_items: 3,
    price_per_item: 182,
    total_price: 532,
    delivery_method: "توصيل بواسطة التاجر",
    notes: "يشمل السعر الضمان لمدة سنة على القطع الأصلية.",
    items: [
      {
        id: "1",
        name: "فلتر هواء",
        price: 148,
        quantity: 1,
        image: "https://images.unsplash.com/photo-1615397349754-c5b2d3f3c9cc",
      },
      {
        id: "2",
        name: "زيت محرك",
        price: 198,
        quantity: 1,
        image: "https://images.unsplash.com/photo-1612831455542-388b1d9f1a0c",
      },
      {
        id: "3",
        name: "بطارية",
        price: 186,
        quantity: 1,
        image: "https://images.unsplash.com/photo-1607860108855-2f6bfecc8a3b",
      },
    ],
  },
  {
    offer_id: "OFR-003",
    id: "12",
    merchant_name: "نوسير",
    merchant_image: "/vendors/Nossir.png",
    merchant_address: "الدمام - حي الشاطئ",
    merchant_rating: 4.3,
    merchant_phone: "+966553214567",
    distance_km: 5.1,
    total_items: 3,
    price_per_item: 178,
    total_price: 504,
    delivery_method: "الاستلام من المتجر",
    notes: "القطع متوفرة حاليًا، يفضّل الاستلام خلال 3 أيام.",
    items: [
      {
        id: "1",
        name: "فلتر هواء",
        price: 152,
        quantity: 1,
        image: "https://images.unsplash.com/photo-1615397349754-c5b2d3f3c9cc",
      },
      {
        id: "2",
        name: "زيت محرك",
        price: 197,
        quantity: 1,
        image: "https://images.unsplash.com/photo-1612831455542-388b1d9f1a0c",
      },
      {
        id: "3",
        name: "بطارية",
        price: 185,
        quantity: 1,
        image: "https://images.unsplash.com/photo-1607860108855-2f6bfecc8a3b",
      },
    ],
  },
  {
    offer_id: "OFR-004",
    id: "2",
    merchant_name: "جير برو",
    merchant_image: "/vendors/GearPro.png",
    merchant_address: "الدمام - حي الريان",
    merchant_rating: 4.5,
    merchant_phone: "+966509876543",
    distance_km: 2.6,
    total_items: 3,
    price_per_item: 181,
    total_price: 541,
    delivery_method: "توصيل بواسطة المنصة",
    notes: "خدمة التوصيل مجانية داخل المدينة.",
    items: [
      {
        id: "1",
        name: "فلتر هواء",
        price: 149,
        quantity: 1,
        image: "https://images.unsplash.com/photo-1615397349754-c5b2d3f3c9cc",
      },
      {
        id: "2",
        name: "زيت محرك",
        price: 201,
        quantity: 1,
        image: "https://images.unsplash.com/photo-1612831455542-388b1d9f1a0c",
      },
      {
        id: "3",
        name: "بطارية",
        price: 191,
        quantity: 1,
        image: "https://images.unsplash.com/photo-1607860108855-2f6bfecc8a3b",
      },
    ],
  },
];
