export const vendors = [
  {
    id: "1",
    name_ar: "كار بارتي هاب",
    name_en: "CarParts Hub",
    image_url: "/vendors/AAT.png",
    rating: 4.5,
    city: "الرياض",
    phone: "+966512345678",
    description: "مورد رئيسي لقطع غيار السيارات الأصلية.",
    lowestBudget: 320,
    distance: 8.2,
    email: "carpartshub@example.com",
    delivery: "التوصيل على التاجر",
    categories: ["جديد", "مستعمل"],
    terms: "تخضع جميع المبيعات لشروط وضمانات الشركة.",
    isOnline: true,
  },
  {
    id: "2",
    name_ar: "جير برو",
    name_en: "GearPro",
    image_url: "/vendors/GearPro.png",
    rating: 4.2,
    city: "جدة",
    phone: "+966512987654",
    description: "متخصص في قطع غيار السيارات والموتوسيكلات.",
    lowestBudget: 190,
    distance: 4.6,
    email: "gearpro@example.com",
    delivery: "التوصيل على المشتري",
    categories: ["مستعمل", "تشليح"],
    terms: "المنتجات المستعملة تُباع كما هي مع مسؤولية محدودة.",
    isOnline: false,
  },
  {
    id: "3",
    name_ar: "أوتو فيكس",
    name_en: "AutoFix",
    image_url: "/vendors/AutoFix.png",
    rating: 4.7,
    city: "الدمام",
    phone: "+966550123456",
    description: "خدمة سريعة وموثوقة لقطع الغيار والصيانة.",
    lowestBudget: 410,
    distance: 12.4,
    email: "autofix@example.com",
    delivery: "التوصيل على التاجر",
    categories: ["جديد"],
    terms: "تضمن الشركة جودة جميع القطع الجديدة لمدة 30 يومًا.",
    isOnline: true,
  },
  {
    id: "4",
    name_ar: "أوتو بارتي برو",
    name_en: "AutoParts Pro",
    image_url: "/vendors/AutoParts.png",
    rating: 4.3,
    city: "مكة",
    phone: "+966511234567",
    description: "أفضل الأسعار لقطع الغيار الأصلية للسيارات.",
    lowestBudget: 270,
    distance: 9.1,
    email: "autopartspro@example.com",
    delivery: "التوصيل على المشتري",
    categories: ["جديد", "مستعمل"],
    terms: "إرجاع القطع الجديدة مقبول خلال 7 أيام مع الفاتورة.",
    isOnline: false,
  },
  {
    id: "5",
    name_ar: "الجميل للسيارات",
    name_en: "Al Gamal Car Accessories",
    image_url: "/vendors/AlGamil.png",
    rating: 4.6,
    city: "الرياض",
    phone: "+966536543210",
    description: "شركة متخصصة في توفير كافة مستلزمات السيارات.",
    lowestBudget: 230,
    distance: 5.7,
    email: "algamal@example.com",
    delivery: "التوصيل على التاجر",
    categories: ["جديد", "تشليح"],
    terms: "الشراء يخضع لشروط الشركة وضمان المنتج الأصلي.",
    isOnline: true,
  },
  {
    id: "6",
    name_ar: "أوتو بارتي",
    name_en: "AutoParts",
    image_url: "/vendors/AutoParts.png",
    rating: 4.1,
    city: "الدمام",
    phone: "+966538947654",
    description: "نقدم قطع غيار عالية الجودة للسيارات.",
    lowestBudget: 80,
    distance: 7.3,
    email: "autoparts@example.com",
    delivery: "التوصيل على المشتري",
    categories: ["مستعمل"],
    terms: "جميع القطع المستعملة تباع كما هي بدون ضمان.",
    isOnline: false,
  },
  {
    id: "7",
    name_ar: "راشد تفاحة",
    name_en: "Rashed Tafa",
    image_url: "/vendors/Apple.png",
    rating: 4.4,
    city: "جدة",
    phone: "+966534567890",
    description: "تخصصنا في قطع غيار السيارات الأوروبية.",
    lowestBudget: 250,
    distance: 6.1,
    email: "rashed@example.com",
    delivery: "التوصيل على التاجر",
    categories: ["جديد", "مستعمل"],
    terms: "تخضع جميع المبيعات لشروط التوصيل وسياسة الاسترجاع.",
    isOnline: true,
  },
  {
    id: "8",
    name_ar: "دوبل إم",
    name_en: "Double M",
    image_url: "/vendors/DoubleM.png",
    rating: 4.8,
    city: "الرياض",
    phone: "+966556789012",
    description: "أفضل العروض على قطع غيار السيارات الفاخرة.",
    lowestBudget: 470,
    distance: 3.4,
    email: "doublem@example.com",
    delivery: "التوصيل على المشتري",
    categories: ["جديد"],
    terms: "المنتجات الجديدة مضمونة لمدة 60 يومًا من تاريخ الشراء.",
    isOnline: false,
  },
  {
    id: "9",
    name_ar: "المتميز لقطع الغيار",
    name_en: "Al Motezaz Auto Parts",
    image_url: "/vendors/Mutamiez.png",
    rating: 4.3,
    city: "الدمام",
    phone: "+966512345678",
    description: "مورد لقطع الغيار لعدة ماركات عالمية.",
    lowestBudget: 210,
    distance: 10.9,
    email: "mutamiez@example.com",
    delivery: "التوصيل على التاجر",
    categories: ["جديد", "تشليح"],
    terms: "السياسة تشمل جميع المنتجات الجديدة والمستعملة حسب الفئة.",
    isOnline: true,
  },
  {
    id: "10",
    name_ar: "أبو غنيمة أدوات السيارات",
    name_en: "Abu Ghnima Car Tools",
    image_url: "/vendors/AG.jpg",
    rating: 4.2,
    city: "مكة",
    phone: "+966551234567",
    description: "مورد أدوات وقطع غيار السيارات بأسعار منافسة.",
    lowestBudget: 70,
    distance: 11.5,
    email: "abughnima@example.com",
    delivery: "التوصيل على المشتري",
    categories: ["مستعمل"],
    terms: "القطع المستعملة تباع كما هي مع إمكانية الاسترجاع خلال 3 أيام.",
    isOnline: false,
  },
  {
    id: "11",
    name_ar: "هووف للسيارات",
    name_en: "Hoof Cars",
    image_url: "/vendors/Hoof.png",
    rating: 4.0,
    city: "جدة",
    phone: "+966559876543",
    description: "نحن نوفر أفضل قطع الغيار للموديلات الحديثة.",
    lowestBudget: 200,
    distance: 9.9,
    email: "hoof@example.com",
    delivery: "التوصيل على التاجر",
    categories: ["جديد", "مستعمل"],
    terms: "تتوفر خدمات الضمان على جميع المنتجات الجديدة.",
    isOnline: true,
  },
  {
    id: "12",
    name_ar: "نوسير لقطع الغيار",
    name_en: "Mossir Auto Parts",
    image_url: "/vendors/Nossir.png",
    rating: 4.7,
    city: "الرياض",
    phone: "+966543210987",
    description: "مورد موثوق لقطع الغيار الأصلية.",
    lowestBudget: 310,
    distance: 2.8,
    email: "mossir@example.com",
    delivery: "التوصيل على التاجر",
    categories: ["جديد"],
    terms: "تتمتع جميع القطع الجديدة بضمان الجودة لمدة 30 يومًا.",
    isOnline: false,
  },
  {
    id: "13",
    name_ar: "نيوسر لقطع الغيار",
    name_en: "Nasser Auto Parts",
    image_url: "/vendors/StoreParts.png",
    rating: 4.5,
    city: "الدمام",
    phone: "+966509876543",
    description: "نوفر قطع غيار بأسعار تنافسية وجودة ممتازة.",
    lowestBudget: 260,
    distance: 6.7,
    email: "nasser@example.com",
    delivery: "التوصيل على المشتري",
    categories: ["جديد", "مستعمل"],
    terms: "سياسة الإرجاع حسب الفئة ونوع القطعة، ضمن 7 أيام من الشراء.",
    isOnline: true,
  },
  {
    id: "14",
    name_ar: "رائد للسيارات",
    name_en: "Al-Sawaf Cars",
    image_url: "/vendors/Raied.jpg",
    rating: 4.4,
    city: "جدة",
    phone: "+966530123456",
    description: "شركة متخصصة في قطع غيار السيارات.",
    lowestBudget: 220,
    distance: 8.6,
    email: "alsawaf@example.com",
    delivery: "التوصيل على التاجر",
    categories: ["مستعمل", "تشليح"],
    terms: "القطع المستعملة تباع كما هي مع سياسة محدودة للاسترجاع.",
    isOnline: false,
  },
  {
    id: "15",
    name_ar: "السواف ",
    name_en: "Store Parts",
    image_url: "/vendors/AlSawwaf.png",
    rating: 4.2,
    city: "مكة",
    phone: "+966520987654",
    description: "مورد قطع غيار السيارات المحلية والعالمية.",
    lowestBudget: 30,
    distance: 12.2,
    email: "storeparts@example.com",
    delivery: "التوصيل على المشتري",
    categories: ["تشليح"],
    terms: "تخضع جميع المبيعات للسياسات العامة للقطع المستعملة.",
    isOnline: true,
  },
  {
    id: "16",
    name_ar: "كار سبير بارتي",
    name_en: "Car Spare Parts",
    image_url: "/vendors/CarSpare.png",
    rating: 4.8,
    city: "الرياض",
    phone: "+966522233344",
    description: "نقدم قطع غيار موثوقة للسيارات بمختلف الأنواع.",
    lowestBudget: 490,
    distance: 4.2,
    email: "carspare@example.com",
    delivery: "التوصيل على التاجر",
    categories: ["جديد"],
    terms: "جميع القطع الجديدة مغطاة بضمان الشركة لمدة 60 يومًا.",
    isOnline: false,
  },
  {
    id: "17",
    name_ar: "شركة الزناد المتحدة",
    name_en: "Al Zannad United Company",
    image_url: "/vendors/Nossir.png",
    rating: 4.3,
    city: "الدمام",
    phone: "+966547654321",
    description: "شركة تقدم جميع أنواع قطع الغيار للسيارات.",
    lowestBudget: 275,
    distance: 7.5,
    email: "alzannad@example.com",
    delivery: "التوصيل على المشتري",
    categories: ["جديد", "مستعمل"],
    terms: "الشراء يخضع لشروط وسياسات الشركة حسب نوع المنتج.",
    isOnline: true,
  },
];
